from __future__ import annotations

from pathlib import Path

from PySide6 import QtCore, QtGui, QtWidgets
from shiboken6 import isValid

from echograph.motion import MotionGenerationService, MotionRequest
from echograph.motion.backends.priormdm import PriorMDMBackend, PriorMDMConfig
from echograph.motion.backends.priormdm.preferences import default_paths
from echograph.motion.backends.handmdm import HandMDMConfig
from echograph.motion.qt_job import MotionJob
from nodes.core import Spec

_CONFIG = PriorMDMConfig()
_HAND_CONFIG = HandMDMConfig()
DEFAULTS = {
    "prompt": "A person walks forward, turns left, and stops.",
    "duration": "5.0", "seed": "42", "guidance": "2.5", "device": "cuda:0",
    "repository": str(_CONFIG.repository), "python": str(_CONFIG.python),
    "checkpoint": "", "dataset": str(_CONFIG.dataset), "output_root": str(_CONFIG.output_root),
    "download_cache": str(_CONFIG.cache_directory),
    "last_bvh": "", "last_archive": "", "last_status": "Ready to configure",
    "animate_hands": "false", "hand_side": "auto", "hand_description": "",
    "preview_profile": "model",
    "hand_start": "0", "hand_end": "0", "hand_blend": "0.15",
    "hand_repository": str(_HAND_CONFIG.repository), "hand_python": str(_HAND_CONFIG.python),
    "hand_checkpoint": str(_HAND_CONFIG.checkpoint),
}


def value(node, key):
    entry = next((p for p in node.params if p.get("name") == key), None)
    if entry is not None:
        return str(entry.get("value", ""))
    return default_paths().get(key, DEFAULTS.get(key, ""))


def set_value(node, scene, key, text):
    params = [dict(p) for p in node.params]
    entry = next((p for p in params if p.get("name") == key), None)
    if entry is None:
        params.append({"name": key, "value": str(text)})
    else:
        entry["value"] = str(text)
    node.params = params
    if scene is not None and isinstance(scene, QtCore.QObject) and not isValid(scene):
        return
    if scene is not None and hasattr(scene, "set_node_params"):
        scene.set_node_params(node.name, params, rebuild=False, emit=True)


def build_ports(item):
    node = item.model
    names = {p.get("name") for p in node.params}
    for key, default in {**DEFAULTS, **default_paths()}.items():
        if key not in names:
            node.params.append({"name": key, "value": default})
    hidden = set(value(node, "__ui_hidden_params").split(",")) | set(DEFAULTS)
    set_value(node, None, "__ui_hidden_params", ",".join(sorted(hidden - {""})))
    from .setup_ui import schedule_setup_offer
    schedule_setup_offer(item)


def config_for_node(node):
    return config_from_paths({key: value(node, key) for key in ("repository", "python", "dataset", "download_cache", "output_root", "checkpoint")},
                             value(node, "device"))


def config_from_paths(values, device):
    defaults = default_paths()
    paths = {key: Path(values[key].strip().strip('"') or defaults[key]).expanduser().resolve()
             for key in ("repository", "python", "dataset", "download_cache", "output_root")}
    checkpoint = values["checkpoint"].strip().strip('"')
    return PriorMDMConfig(**paths, checkpoint=Path(checkpoint).expanduser().resolve() if checkpoint else None,
                          device=device.strip())


def create_preview_node(node, scene, bvh: Path):
    if scene is None or not hasattr(scene, "add_node"):
        return False
    from echograph.model import GraphNode
    from nodes import mocap_import
    mocap_import.register()
    name = scene._unique_node_name("PriorMDM_Motion", "mocap_import")
    source = getattr(scene, "_node_items", {}).get(node.name)
    pos = source.scenePos() + QtCore.QPointF(source.width + 90, 0) if source else QtCore.QPointF()
    preview = GraphNode(name=name, kind="mocap_import", info=f"Generated by {node.name}; reconstructed BVH preview",
                        params=[{"name": "path", "value": str(bvh)}])
    preview.pos_xy = (pos.x(), pos.y())
    preview.pos = pos
    scene.add_node(preview, pos)
    if callable(getattr(scene, "on_info", None)):
        scene.on_info(preview)
    return True


class MotionControls(QtWidgets.QWidget):
    def __init__(self, node, scene=None, parent=None):
        super().__init__(parent)
        self.node, self.graph_scene = node, scene
        layout = QtWidgets.QVBoxLayout(self)
        setup_group = QtWidgets.QGroupBox("Model setup")
        setup_layout = QtWidgets.QVBoxLayout(setup_group)
        setup_row = QtWidgets.QHBoxLayout()
        self.check_button = QtWidgets.QPushButton("Setup PriorMDM")
        self.hand_setup_button = QtWidgets.QPushButton("Setup HandMDM")
        for button, tip in ((self.check_button, "Body motion model: manage its environment and checkpoint."),
                            (self.hand_setup_button, "Finger motion model: manage its separate environment and checkpoint.")):
            button.setAutoDefault(False)
            button.setDefault(False)
            button.setStyleSheet("QPushButton { background-color: palette(button); color: palette(button-text); border: 1px solid palette(mid); border-radius: 4px; padding: 6px; } QPushButton:focus { border: 1px solid palette(highlight); } QPushButton:disabled { color: palette(mid); }")
            button.setToolTip(tip)
            setup_row.addWidget(button)
        setup_layout.addLayout(setup_row)
        self.hands_enabled = QtWidgets.QCheckBox("Add hand articulation")
        self.hands_enabled.setChecked(value(node, "animate_hands").lower() == "true")
        setup_layout.addWidget(self.hands_enabled)
        layout.addWidget(setup_group)
        self.prompt = QtWidgets.QPlainTextEdit(value(node, "prompt"))
        self.prompt.setPlaceholderText("Describe one character's motion")
        self.prompt.setFixedHeight(80)
        layout.addWidget(QtWidgets.QLabel("Motion prompt"))
        layout.addWidget(self.prompt)
        form = QtWidgets.QFormLayout()
        self.duration = QtWidgets.QDoubleSpinBox()
        self.duration.setRange(0.1, 9.8)
        self.duration.setSingleStep(0.05)
        self.duration.setDecimals(2)
        self.duration.setSuffix(" s (20 fps)")
        self.duration.setValue(float(value(node, "duration")))
        self.seed = QtWidgets.QLineEdit(value(node, "seed"))
        self.seed.setValidator(QtGui.QRegularExpressionValidator(QtCore.QRegularExpression(r"\d{1,10}"), self.seed))
        self.guidance = QtWidgets.QDoubleSpinBox()
        self.guidance.setRange(0, 20)
        self.guidance.setSingleStep(0.1)
        self.guidance.setValue(float(value(node, "guidance")))
        self.device = QtWidgets.QComboBox()
        self.device.setEditable(True)
        self.device.addItems(["cuda:0", "cpu"])
        self.device.setCurrentText(value(node, "device"))
        for label, widget in (("Duration", self.duration), ("Seed", self.seed), ("Guidance", self.guidance), ("Device", self.device)):
            form.addRow(label, widget)
        layout.addLayout(form)
        self.proportions = QtWidgets.QComboBox()
        self.proportions.addItem("Original model proportions", "model")
        self.proportions.addItem("StandardMan reference — basic body joints", "standardman")
        self.proportions.setCurrentIndex(max(0, self.proportions.findData(value(node, "preview_profile"))))
        self.proportions.setToolTip("Changes the exported preview's proportions. Original motion data is preserved. Reference proportions may need foot/contact cleanup.")
        form.addRow("Preview proportions", self.proportions)
        self.proportions.currentIndexChanged.connect(lambda: self._persist("preview_profile", self.proportions.currentData()))
        self.hand_mode = QtWidgets.QLabel()
        self.hand_mode.setWordWrap(True)
        layout.addWidget(self.hand_mode)
        self.hand_options = QtWidgets.QWidget()
        hand_form = QtWidgets.QFormLayout(self.hand_options)
        hand_form.setContentsMargins(0, 0, 0, 0)
        self.hand_side = QtWidgets.QComboBox()
        self.hand_side.addItems(["auto", "right", "left", "both"])
        self.hand_side.setCurrentText(value(node, "hand_side"))
        self.hand_description = QtWidgets.QLineEdit(value(node, "hand_description"))
        self.hand_description.setPlaceholderText("Optional: describe the fingers; leave blank for point, fist, open palm, peace or thumbs-up")
        hand_form.addRow("Hand", self.hand_side)
        hand_form.addRow("Hand description", self.hand_description)
        self.hand_times = {}
        for key, label in (("hand_start", "Gesture start"), ("hand_end", "Gesture end"), ("hand_blend", "Blend")):
            spin = QtWidgets.QDoubleSpinBox()
            spin.setRange(0, 9.8)
            spin.setDecimals(2)
            spin.setSingleStep(0.05)
            spin.setSuffix(" s")
            spin.setValue(float(value(node, key)))
            if key == "hand_end":
                spin.setSpecialValueText("End of body clip")
            self.hand_times[key] = spin
            hand_form.addRow(label, spin)
            spin.valueChanged.connect(lambda number, k=key: self._persist(k, number))
        hand_note = QtWidgets.QLabel("Hands play a short gesture, hold, then blend out. The finger skeleton is a preview; precise palm orientation and character retargeting need refinement.")
        hand_note.setWordWrap(True)
        hand_form.addRow(hand_note)
        self.hand_options.setVisible(self.hands_enabled.isChecked())
        self.hands_enabled.toggled.connect(self.hand_options.setVisible)
        self.hands_enabled.toggled.connect(lambda checked: self._persist("animate_hands", str(checked).lower()))
        self.hand_side.currentTextChanged.connect(lambda text: self._persist("hand_side", text))
        self.hand_description.textChanged.connect(lambda text: self._persist("hand_description", text))
        layout.addWidget(self.hand_options)
        self.hand_setup_button.clicked.connect(self._hand_setup)
        self.advanced_button = QtWidgets.QToolButton()
        self.advanced_button.setText("Advanced paths")
        self.advanced_button.setCheckable(True)
        self.advanced_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.advanced_button.setArrowType(QtCore.Qt.RightArrow)
        layout.addWidget(self.advanced_button)
        self.advanced_paths = QtWidgets.QWidget()
        advanced_form = QtWidgets.QFormLayout(self.advanced_paths)
        advanced_form.setContentsMargins(0, 0, 0, 0)
        self.paths = {}
        for key, label, directory in (("checkpoint", "Checkpoint (.pt)", False),
                                       ("repository", "PriorMDM folder", True),
                                       ("python", "Inference Python", False),
                                       ("dataset", "Normalization folder", True),
                                       ("download_cache", "Download cache", True),
                                       ("output_root", "Output folder", True),
                                       ("hand_repository", "HandMDM folder", True),
                                       ("hand_python", "Hand inference Python", False),
                                       ("hand_checkpoint", "Hand checkpoint (.ckpt)", False)):
            row = QtWidgets.QWidget()
            row_layout = QtWidgets.QHBoxLayout(row)
            row_layout.setContentsMargins(0, 0, 0, 0)
            edit = QtWidgets.QLineEdit(value(node, key))
            edit.setPlaceholderText(default_paths().get(key, DEFAULTS.get(key, "")) if key != "checkpoint" else "Selected automatically during setup")
            self.paths[key] = edit
            browse = QtWidgets.QPushButton("Browse")
            browse.clicked.connect(lambda checked=False, k=key, d=directory: self._browse(k, d))
            row_layout.addWidget(edit, 1)
            row_layout.addWidget(browse)
            advanced_form.addRow(label, row)
            edit.editingFinished.connect(lambda k=key: self._persist(k, self.paths[k].text()))
        self.advanced_paths.hide()
        self.advanced_button.toggled.connect(self.advanced_paths.setVisible)
        self.advanced_button.toggled.connect(lambda expanded: self.advanced_button.setArrowType(
            QtCore.Qt.DownArrow if expanded else QtCore.Qt.RightArrow))
        layout.addWidget(self.advanced_paths)
        note = QtWidgets.QLabel("Setup selects the model and shared data folders automatically. BVH uses reconstructed rotations for skeleton preview and blocking.")
        note.setWordWrap(True)
        layout.addWidget(note)
        buttons = QtWidgets.QHBoxLayout()
        self.generate_button = QtWidgets.QPushButton("Generate")
        self.generate_button.setStyleSheet(
            "QPushButton { background: #27834a; color: #ffffff; border: 1px solid #34995a; border-radius: 4px; padding: 8px 12px; }"
            "QPushButton:hover:enabled { background: #319b58; }"
            'QPushButton[cancelling="true"] { background: #b91c1c; color: #ffffff; border-color: #ef4444; }'
            'QPushButton[cancelling="true"]:hover { background: #dc2626; }'
            "QPushButton:disabled { background: #374151; color: #d1d5db; border-color: #4b5563; }"
        )
        self.preview_button = QtWidgets.QPushButton("Create MocapBVH")
        self.tpose_button = QtWidgets.QPushButton("Create T-pose BVH")
        self.apose_button = QtWidgets.QPushButton("Create A-pose BVH")
        self.apose_button.setToolTip("Create a separate, single-frame rig with arms lowered 45 degrees, using the last generated skeleton.")
        self.tpose_button.setToolTip("Create a separate, single-frame T-pose rig from the last generated skeleton, preserving its proportions and finger joints.")
        self.open_button = QtWidgets.QPushButton("Open result folder")
        self.generate_button.setAutoDefault(False)
        buttons.addWidget(self.generate_button)
        layout.addLayout(buttons)
        exports = QtWidgets.QHBoxLayout()
        for button in (self.preview_button, self.tpose_button, self.apose_button, self.open_button):
            button.setAutoDefault(False)
            exports.addWidget(button)
        layout.addLayout(exports)
        for button in self.findChildren(QtWidgets.QPushButton):
            button.setMinimumHeight(max(36, button.sizeHint().height()))
        self.advanced_button.setMinimumHeight(32)
        self.status = QtWidgets.QLabel(value(node, "last_status"))
        self.status.setWordWrap(True)
        self.log = QtWidgets.QPlainTextEdit()
        self.log.setReadOnly(True)
        self.log.setMaximumBlockCount(500)
        self.log.setMinimumHeight(115)
        layout.addWidget(self.status)
        layout.addWidget(self.log)
        self.prompt.textChanged.connect(lambda: self._persist("prompt", self.prompt.toPlainText()))
        self.duration.valueChanged.connect(lambda v: self._persist("duration", v))
        self.seed.editingFinished.connect(lambda: self._persist("seed", self.seed.text()))
        self.guidance.valueChanged.connect(lambda v: self._persist("guidance", v))
        self.device.currentTextChanged.connect(lambda v: self._persist("device", v))
        self.generate_button.clicked.connect(self._generate)
        self.hands_enabled.toggled.connect(self._refresh_buttons)
        self.check_button.clicked.connect(self._check)
        self.preview_button.clicked.connect(self._preview)
        self.tpose_button.clicked.connect(self._tpose)
        self.apose_button.clicked.connect(lambda: self._static_pose("apose"))
        self.open_button.clicked.connect(self._open_result)
        job = getattr(node, "_motion_job", None)
        if job and job.running:
            self._connect_job(job)
            self.log.setPlainText(job.log_text)
        self._setup_session = None
        session = getattr(node, "_prior_setup_session", None)
        if session is not None:
            self._connect_setup(session)
        self._refresh()
        from .hand_setup_ui import hand_setup_session, register_node
        register_node(node)
        hand_setup_session().changed.connect(self._refresh_buttons)
        self.prompt.setFocus(QtCore.Qt.OtherFocusReason)

    def _persist(self, key, text):
        set_value(self.node, self.graph_scene, key, text)

    def _browse(self, key, directory):
        current = self.paths[key].text()
        if directory:
            selected = QtWidgets.QFileDialog.getExistingDirectory(self, "Select folder", current)
        else:
            filter_text = ("Checkpoint (*.pt *.ckpt)" if key in ("checkpoint", "hand_checkpoint")
                           else "Python executable (python.exe python);;All files (*)")
            selected, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select file", current, filter_text)
        if selected:
            self.paths[key].setText(selected)
            self._persist(key, selected)

    def _service(self):
        config = config_from_paths({key: edit.text() for key, edit in self.paths.items()}, self.device.currentText())
        backend = PriorMDMBackend(config, preview_profile=self.proportions.currentData())
        if self.hands_enabled.isChecked():
            from echograph.motion.combined import BodyHandBackend
            hand = HandMDMConfig(**{key: Path(self.paths['hand_' + key].text().strip().strip('"')
                                            or str(getattr(_HAND_CONFIG, key))).expanduser().resolve()
                                   for key in ("repository", "python", "checkpoint")}, device=config.device)
            backend = BodyHandBackend(backend, hand, side=self.hand_side.currentText(),
                                      description=self.hand_description.text(),
                                      start=self.hand_times["hand_start"].value(),
                                      end=self.hand_times["hand_end"].value() or None,
                                      blend=self.hand_times["hand_blend"].value())
        return MotionGenerationService(backend)

    def _hand_setup(self):
        from .hand_setup_ui import show_hand_setup
        show_hand_setup(self.node, self.graph_scene)

    def _check(self):
        try:
            for key, edit in self.paths.items():
                self._persist(key, edit.text())
            from .setup_ui import show_setup
            dialog = show_setup(self.node, self.graph_scene)
            self._connect_setup(dialog.session)
        except Exception as exc:
            self.status.setText(str(exc))

    def _connect_setup(self, session):
        if self._setup_session is session:
            return
        if self._setup_session is not None:
            self._setup_session.finished.disconnect(self._setup_finished)
            self._setup_session.changed.disconnect(self._setup_changed)
        self._setup_session = session
        session.finished.connect(self._setup_finished)
        session.changed.connect(self._setup_changed)
        self._refresh_buttons()

    @QtCore.Slot()
    def _setup_changed(self):
        session = getattr(self.node, "_prior_setup_session", None)
        if session is not None and session is not self._setup_session:
            self._connect_setup(session)
            for key, edit in self.paths.items():
                edit.setText(value(self.node, key))
        self._refresh_buttons()

    @QtCore.Slot(object)
    def _setup_finished(self, report):
        if not report.get("failed") and not report.get("cancelled"):
            for key in ("checkpoint", "python", "dataset", "download_cache"):
                self.paths[key].setText(value(self.node, key))
            self.device.setCurrentText(value(self.node, "device"))
        self._refresh()

    def _generate(self):
        if getattr(self.node, "_motion_job", None) and self.node._motion_job.running:
            self._cancel()
            return
        try:
            from .setup_ui import active_installation
            if active_installation(self._service().backend.config.repository):
                self.status.setText("Wait for PriorMDM setup to finish before generating.")
                return
            from .hand_setup_ui import hand_setup_session
            if self.hands_enabled.isChecked() and hand_setup_session().running:
                self.status.setText("Wait for HandMDM setup to finish before generating hands.")
                return
            for key, edit in self.paths.items():
                self._persist(key, edit.text())
            self._persist("seed", self.seed.text())
            service = self._service()
            plan = service.prepare(MotionRequest(self.prompt.toPlainText(), self.duration.value(), int(self.seed.text()), self.guidance.value()))
            old_job = getattr(self.node, "_motion_job", None)
            if old_job is not None:
                old_job.deleteLater()
            job = MotionJob(service, plan, QtWidgets.QApplication.instance())
            self.node._motion_job = job
            node, scene = self.node, self.graph_scene
            # Persist completion even when the controls have been closed/rebuilt.
            def done(result):
                set_value(node, scene, "last_bvh", str(result.bvh_path))
                set_value(node, scene, "last_archive", str(result.archive_path))
                mode = "body + fingers" if result.bvh_path.name == "preview_hands.bvh" else "body only (no fingers)"
                set_value(node, scene, "last_status", f"Complete: {mode}. Create a new MocapBVH node to preview this result.")
            job.completed.connect(done)
            job.failed.connect(lambda message: set_value(node, scene, "last_status", message))
            self._connect_job(job)
            self.log.clear()
            self._persist("last_status", "Generating…")
            job.start()
            self._refresh()
        except Exception as exc:
            self.status.setText(str(exc))
            self._refresh_buttons()

    def _connect_job(self, job):
        job.output.connect(self._append_log)
        job.completed.connect(self._completed)
        job.failed.connect(self._failed)

    @QtCore.Slot(str)
    def _append_log(self, text):
        cursor = self.log.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.log.setTextCursor(cursor)

    @QtCore.Slot(object)
    def _completed(self, result):
        self._refresh()

    @QtCore.Slot(str)
    def _failed(self, message):
        self._refresh()

    def _refresh_buttons(self):
        enabled = self.hands_enabled.isChecked()
        self.hand_setup_button.setVisible(enabled)
        self.hand_mode.setText(
            "Hand generation enabled. For dancing or other custom actions, enter a hand description below."
            if enabled else "Body only: enable Add hand articulation to generate fingers. HandMDM setup installs resources; it does not enable this option.")
        job = getattr(self.node, "_motion_job", None)
        running = bool(job and job.running)
        setup = getattr(self.node, "_prior_setup_session", None)
        setup_running = bool(setup and setup.running)
        from .hand_setup_ui import hand_setup_session
        setup_running = setup_running or (self.hands_enabled.isChecked() and hand_setup_session().running)
        self.generate_button.setText("Cancel generation" if running else (
            "Generate body + hands" if enabled else "Generate body only"))
        self.generate_button.setToolTip("Stop the current generation." if running else "Generate motion from the prompt.")
        if self.generate_button.property("cancelling") != running:
            self.generate_button.setProperty("cancelling", running)
            self.generate_button.style().unpolish(self.generate_button)
            self.generate_button.style().polish(self.generate_button)
            self.generate_button.update()
        self.generate_button.setEnabled(running or not setup_running)
        self.check_button.setEnabled(not running)
        self.hand_setup_button.setEnabled(not running)
        self.hands_enabled.setEnabled(not running)
        self.proportions.setEnabled(not running)
        self.hand_options.setEnabled(not running)
        for edit in self.paths.values():
            edit.parentWidget().setEnabled(not setup_running)
        self.device.setEnabled(not setup_running)
        available = bool(value(self.node, "last_bvh")) and Path(value(self.node, "last_bvh")).is_file()
        self.preview_button.setEnabled(available)
        self.tpose_button.setEnabled(available)
        self.apose_button.setEnabled(available)
        last_has_hands = Path(value(self.node, "last_bvh")).name == "preview_hands.bvh"
        self.preview_button.setText("Create MocapBVH" + (" (hands)" if last_has_hands else " (body only)") if available else "Create MocapBVH")
        self.preview_button.setToolTip("Loads the last completed result. Changing hand options requires generating again; existing MocapBVH nodes keep their previous file.")
        self.open_button.setEnabled(available)

    def _refresh(self):
        self.status.setText(value(self.node, "last_status"))
        self._refresh_buttons()

    def _cancel(self):
        job = getattr(self.node, "_motion_job", None)
        if job:
            job.cancel()

    def _preview(self):
        try:
            if not create_preview_node(self.node, self.graph_scene, Path(value(self.node, "last_bvh"))):
                self.status.setText("Open these controls from a graph to create the preview node.")
        except Exception as exc:
            self.status.setText(f"Could not create preview: {exc}")

    def _tpose(self):
        self._static_pose("tpose")

    def _static_pose(self, pose):
        label = "A-pose" if pose == "apose" else "T-pose"
        try:
            from echograph.motion.conversion import create_static_pose_bvh
            path = create_static_pose_bvh(Path(value(self.node, "last_bvh")), pose)
            create_preview_node(self.node, self.graph_scene, path)
            self.status.setText(f"Static {label} rig created: {path}")
        except Exception as exc:
            self.status.setText(f"Could not create {label}: {exc}")

    def _open_result(self):
        QtGui.QDesktopServices.openUrl(QtCore.QUrl.fromLocalFile(str(Path(value(self.node, "last_bvh")).parent)))


def open_controls(item):
    node = item.model
    dialog = getattr(node, "_motion_dialog", None)
    if dialog is None:
        views = item.scene().views() if item.scene() is not None else []
        owner = views[0].window() if views else QtWidgets.QApplication.activeWindow()
        dialog = QtWidgets.QDialog(owner)
        dialog.setWindowModality(QtCore.Qt.NonModal)
        # This auxiliary window must not keep the application alive after its
        # main window closes. Also close hidden/reopened instances on shutdown.
        dialog.setAttribute(QtCore.Qt.WA_QuitOnClose, False)
        QtWidgets.QApplication.instance().aboutToQuit.connect(dialog.close)
        dialog.setWindowTitle("PriorMDM — Text to Motion")
        screen = QtWidgets.QApplication.primaryScreen()
        available = screen.availableGeometry() if screen else QtCore.QRect(0, 0, 1100, 1100)
        dialog.resize(min(960, available.width() - 40), min(1020, available.height() - 60))
        layout = QtWidgets.QVBoxLayout(dialog)
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(MotionControls(node, item.scene(), scroll))
        layout.addWidget(scroll)
        node._motion_dialog = dialog
    dialog.show()
    dialog.raise_()
    dialog.activateWindow()


def render_node_body(item, y_cursor):
    body = QtWidgets.QWidget()
    layout = QtWidgets.QVBoxLayout(body)
    layout.setContentsMargins(8, 6, 8, 8)
    label = QtWidgets.QLabel("Text → humanoid animation")
    label.setWordWrap(True)
    button = QtWidgets.QPushButton("Open PriorMDM")
    button.clicked.connect(lambda: open_controls(item))
    setup_button = QtWidgets.QPushButton("Setup PriorMDM")
    setup_button.setAutoDefault(False)
    def open_setup():
        from .setup_ui import show_setup
        show_setup(item.model, item.scene())
    setup_button.clicked.connect(open_setup)
    layout.addWidget(label)
    layout.addWidget(button)
    layout.addWidget(setup_button)
    hand_setup = QtWidgets.QPushButton("Setup HandMDM")
    hand_setup.setAutoDefault(False)
    def open_hand_setup():
        from .hand_setup_ui import show_hand_setup
        show_hand_setup(item.model, item.scene())
    hand_setup.clicked.connect(open_hand_setup)
    layout.addWidget(hand_setup)
    body.setFixedWidth(int(item.width))
    body.ensurePolished()
    height = max(body.sizeHint().height(), body.minimumSizeHint().height())
    proxy = QtWidgets.QGraphicsProxyWidget(item)
    proxy.setWidget(body)
    proxy.setPos(0, y_cursor)
    proxy.resize(item.width, height)
    item._plugin_proxies.append(proxy)
    bottom = y_cursor + height + 10
    item.prepareGeometryChange()
    item.height = max(item.height, bottom)
    return bottom


def augment_infocard_footer(card, footer_layout):
    node = getattr(card, "_node_ref", None)
    if node is None or node.kind.lower() != "priormdm":
        return False
    footer_layout.addWidget(MotionControls(node, getattr(card, "_graph_scene", None), card))
    return True


PRIORMDM_SPEC = Spec(stripe_color="#a78bfa", build_ports=build_ports,
                     render_node_body=render_node_body, augment_infocard_footer=augment_infocard_footer)
